# The reference genome, used for the mapping
reference:
  /Users/tilro532/rackstore/ref_gg6a/ref_unzipped/GCF_000002315.5_GRCg6a_genomic.fna

# If we want to have an output that contains only the sites selected between 2 lines #TODO needed? FIXME
selectBetweenLines:
  /Users/tilro532/wd/stripes_2_data/Founder_fixed_sites_chr_sites.txt

# Folder containing the fastq (considered as paired and named {sample}_forward.fastq.gz and {sample}_reverse.fastq.gz)
Raw_Folder:
  /Users/tilro532/wd/stripes_2_data/raw

# file containing all sample wildcards, in case no individual input files are there anymore
# TODO have this derived from the VCF samples ?
sample_file:
  /Users/tilro532/wd/stripes_2_data/input_aux/sample_names_F2_new.txt


# The VCF file of founders (created separatly with a more classic approach, in our case GATK and a joined call)
founders:
  /Users/tilro532/rackstore/all_GQ20_MQ50_noIndels_callrate0.3.vcf

TIGER_WD:
  /Users/tilro532/wd/stripes_2_data/data

CALL_WD:
  VCF

cohort:
  /Users/tilro532/rackstore/F2/all_f2_only_founder_snps_new_names.vcf

# Was used to test the difference of quality in pipeline using markers fixed in family and in line
indiv:
  fam:
    with.fam.f2.call2.
#  lines: with.lines.f2.call2.

# To create a folder of the VCFs
CALLING_SUFFIX:
  Call

# To create a folder for individual genotypes per sample
GENOTYPE_SUFFIX:
  Genotype


# The results of TIGER, one subfolder per sample, splited by chromosomes
TIGER_SUFFIX:
  TIGER_OUT


# A file with the chromosomes and their size in base (see example)
genomeSizeFile:
  /Users/tilro532/wd/stripes_2_data/size.genome


# Number of SNP per windows
winsize:
  50

# Number of scaffolds to treat (Take the scaffold numbered (1-scaffoldNumber), the methods is not working well for smaller scaffold
scaffoldNumber:
  25

# The pedigree file (see example for format)
pedigree:
  /Users/tilro532/wd/stripes_2_data/input_aux/combined_pedigree_20181217.tsv

# File containing the full names (from the reference, a rank (col 3) and the size of the chromosomes
contigNames:
  /Users/tilro532/wd/stripes_2_data/input_aux/Index_fastq_contig_chr.txt


# If not in the script folder use an absolute path
individualGenotypes2breaksPath:
  individualGenotypes2breaks

high:
  /Users/tilro532/wd/stripes_2_data/input_aux/high_full.txt
low:
  /Users/tilro532/wd/stripes_2_data/input_aux/low_full.txt
generation:
  2
